repository:
  name: microservice-bootstrap-operator
  description: A Kubernetes operator for automating microservice bootstrapping and secret rotation
  homepage: https://kannann1.github.io/microservice-bootstrap-operator
  topics:
    - kubernetes
    - operator
    - microservice
    - java
    - secret-rotation
    - sidecar-injection
    - kubernetes-operator
  private: false
  has_issues: true
  has_projects: true
  has_wiki: true
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  delete_branch_on_merge: true

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts:
          - "Build and Test"
          - "Build and Push Docker Image"
      enforce_admins: false
      restrictions: null

labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  - name: good first issue
    color: 7057ff
    description: Good for newcomers
  - name: help wanted
    color: 008672
    description: Extra attention is needed
