---
# Sample AppConfig with default secret rotation strategy
apiVersion: microservice.example.com/v1
kind: AppConfig
metadata:
  name: default-rotation-app
  namespace: default
spec:
  appName: default-rotation-app
  githubRepo: https://github.com/example/app-config
  githubRef: main
  configPath: /config
  secretRotation:
    enabled: true
    intervalHours: 24
    strategy: default
    sources:
      - internal

---
# Sample AppConfig with database credentials rotation strategy
apiVersion: microservice.example.com/v1
kind: AppConfig
metadata:
  name: db-rotation-app
  namespace: default
spec:
  appName: db-rotation-app
  githubRepo: https://github.com/example/app-config
  githubRef: main
  configPath: /config
  secretRotation:
    enabled: true
    intervalHours: 48
    strategy: database
    sources:
      - postgresql
    strategyConfig:
      dbType: postgresql
      dbHost: postgres.default.svc.cluster.local
      dbPort: "5432"

---
# Sample AppConfig with API key rotation strategy
apiVersion: microservice.example.com/v1
kind: AppConfig
metadata:
  name: api-rotation-app
  namespace: default
spec:
  appName: api-rotation-app
  githubRepo: https://github.com/example/app-config
  githubRef: main
  configPath: /config
  secretRotation:
    enabled: true
    intervalHours: 168  # Weekly rotation
    strategy: api-key
    sources:
      - external-api
    strategyConfig:
      keyLength: "32"
      secretLength: "64"

---
# Sample AppConfig with TLS certificate rotation strategy
apiVersion: microservice.example.com/v1
kind: AppConfig
metadata:
  name: tls-rotation-app
  namespace: default
spec:
  appName: tls-rotation-app
  githubRepo: https://github.com/example/app-config
  githubRef: main
  configPath: /config
  secretRotation:
    enabled: true
    intervalHours: 720  # 30 days
    strategy: tls
    sources:
      - cert-manager
    strategyConfig:
      commonName: "api.example.com"
      organization: "Example Corp"
      validityDays: "90"

---
# Sample AppConfig with all features enabled
apiVersion: microservice.example.com/v1
kind: AppConfig
metadata:
  name: full-featured-app
  namespace: default
spec:
  appName: full-featured-app
  githubRepo: https://github.com/example/app-config
  githubRef: main
  configPath: /config
  
  # Secret rotation configuration
  secretRotation:
    enabled: true
    intervalHours: 24
    strategy: database
    sources:
      - postgresql
      - redis
    strategyConfig:
      dbType: postgresql
      redisHost: redis.default.svc.cluster.local
  
  # Sidecar injection configuration
  sidecarInjection:
    enabled: true
    name: logging-sidecar
    image: fluent/fluent-bit:latest
    selectorLabels:
      app: full-featured-app
      component: web
    env:
      LOG_LEVEL: info
      FLUSH_INTERVAL: "5"
    volumes:
      - config-volume
    volumeMounts:
      config-volume: /fluent-bit/etc
  
  # RBAC configuration
  rbac:
    enabled: true
    serviceAccountName: full-featured-app-sa
    roles:
      - full-featured-app-reader
      - full-featured-app-writer
    roleBindings:
      - full-featured-app-reader-binding
      - full-featured-app-writer-binding
  
  # Network policy configuration
  networkPolicy:
    enabled: true
