apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: appconfigs.microservice.github.io
spec:
  group: microservice.github.io
  names:
    kind: AppConfig
    listKind: AppConfigList
    plural: appconfigs
    singular: appconfig
    shortNames:
      - ac
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                appName:
                  type: string
                  description: "Application name"
                githubRepo:
                  type: string
                  description: "GitHub repository URL containing configuration templates"
                githubRef:
                  type: string
                  description: "Branch or tag to use from the GitHub repository"
                configPath:
                  type: string
                  description: "Path within the repository where config templates are stored"
                sidecars:
                  type: array
                  description: "Legacy field - List of sidecars to inject"
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      image:
                        type: string
                sidecarInjection:
                  type: object
                  description: "Sidecar injection configuration"
                  properties:
                    enabled:
                      type: boolean
                      description: "Whether sidecar injection is enabled"
                    name:
                      type: string
                      description: "Name of the sidecar container"
                    image:
                      type: string
                      description: "Docker image for the sidecar"
                    selectorLabels:
                      type: object
                      description: "Labels to select pods for sidecar injection"
                      additionalProperties:
                        type: string
                    env:
                      type: object
                      description: "Environment variables for the sidecar"
                      additionalProperties:
                        type: string
                    volumes:
                      type: array
                      description: "Volumes to create for the sidecar"
                      items:
                        type: string
                    volumeMounts:
                      type: object
                      description: "Volume mounts for the sidecar (volume name -> mount path)"
                      additionalProperties:
                        type: string
                secretRotation:
                  type: object
                  description: "Secret rotation configuration"
                  properties:
                    enabled:
                      type: boolean
                      description: "Enable secret rotation"
                    intervalHours:
                      type: integer
                      description: "Rotation interval in hours"
                      default: 24
                    sources:
                      type: array
                      description: "Secret sources to rotate"
                      items:
                        type: string
                    strategy:
                      type: string
                      description: "Rotation strategy to use (default, database, api-key, tls)"
                      default: "default"
                      enum: ["default", "database", "api-key", "tls"]
                    strategyConfig:
                      type: object
                      description: "Additional configuration parameters for the rotation strategy"
                      additionalProperties:
                        type: string
                rbac:
                  type: object
                  description: "RBAC configuration"
                  properties:
                    enabled:
                      type: boolean
                    serviceAccountName:
                      type: string
                    rules:
                      type: array
                      items:
                        type: object
                        properties:
                          apiGroups:
                            type: array
                            items:
                              type: string
                          resources:
                            type: array
                            items:
                              type: string
                          verbs:
                            type: array
                            items:
                              type: string
                networkPolicy:
                  type: object
                  description: "Network policy configuration"
                  properties:
                    enabled:
                      type: boolean
                    ingressRules:
                      type: array
                      items:
                        type: object
                        properties:
                          from:
                            type: array
                            items:
                              type: object
                              properties:
                                podSelector:
                                  type: object
                                  properties:
                                    matchLabels:
                                      type: object
                                      additionalProperties:
                                        type: string
                                namespaceSelector:
                                  type: object
                                  properties:
                                    matchLabels:
                                      type: object
                                      additionalProperties:
                                        type: string
                          ports:
                            type: array
                            items:
                              type: object
                              properties:
                                port:
                                  type: integer
                                protocol:
                                  type: string
                                  enum: ["TCP", "UDP", "SCTP"]
              required:
                - appName
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                createdResources:
                  type: array
                  items:
                    type: string
                lastRotationTime:
                  type: string
                  format: date-time
      additionalPrinterColumns:
        - name: App
          type: string
          jsonPath: .spec.appName
        - name: Status
          type: string
          jsonPath: .status.conditions[?(@.type=="Ready")].status
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      subresources:
        status: {}
